# Creating Classification Models using<code> Keras & TensorFlow</code>
----
1. Use <code>categorical_crossentropy</code> as loss function
- Similar to log loss: **Lower is better**
- Add <code>metrics = ['accuracy']</code> to compile step for easy-to-understand diagnostics
- Output layer should has separate node for each possible outcome
-uses <code>softmax</code> activation

## Scenerio: Predict survival on the Titanic disaster
1. Modelling with a dataset "Titanic" for a classification problem
- You will use predictors/inputs such as 
    - age
    - fare
    - embarked
    - .. etc to predict who will survive.



### 1. Import required modules

In [57]:
import pandas as pd
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense

### 2. Import the train and test datadata

#### 2.1 Load Train Data

In [30]:
# understand data
df = pd.read_csv("titanic_all_numeric_train.csv")
df.head()

survived  pclass   age  sibsp  parch     fare  male  age_was_missing  \
0         0       3  22.0      1      0   7.2500     1            False   
1         1       1  38.0      1      0  71.2833     0            False   
2         1       3  26.0      0      0   7.9250     0            False   
3         1       1  35.0      1      0  53.1000     0            False   
4         0       3  35.0      0      0   8.0500     1            False   

   embarked_from_cherbourg  embarked_from_queenstown  \
0                        0                         0   
1                        1                         0   
2                        0                         0   
3                        0                         0   
4                        0                         0   

   embarked_from_southampton  
0                          1  
1                          0  
2                          1  
3                          1  
4                          1

In [31]:
X_train = df.drop(['survived'], axis=1).values

In [32]:
X_train[:5]

array([[3, 22.0, 1, 0, 7.25, 1, False, 0, 0, 1],
       [1, 38.0, 1, 0, 71.2833, 0, False, 1, 0, 0],
       [3, 26.0, 0, 0, 7.925, 0, False, 0, 0, 1],
       [1, 35.0, 1, 0, 53.1, 0, False, 0, 0, 1],
       [3, 35.0, 0, 0, 8.05, 1, False, 0, 0, 1]], dtype=object)

In [33]:
df.survived[:5]

0    0
1    1
2    1
3    1
4    0
Name: survived, dtype: int64

In [34]:
y_train = to_categorical(df.survived)

In [35]:
type(y_train)

numpy.ndarray

In [36]:
y_train[:5]

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.]], dtype=float32)

#### 2.2 Load Test Data

In [37]:
df = pd.read_csv("titanic_all_numeric_test.csv")

In [38]:
df.head()

survived  pclass   age  sibsp  parch     fare  male  age_was_missing  \
0         0       3  22.0      1      0   7.2500     1            False   
1         1       1  38.0      1      0  71.2833     0            False   
2         1       3  26.0      0      0   7.9250     0            False   
3         1       1  35.0      1      0  53.1000     0            False   
4         0       3  35.0      0      0   8.0500     1            False   

   embarked_from_cherbourg  embarked_from_queenstown  \
0                        0                         0   
1                        1                         0   
2                        0                         0   
3                        0                         0   
4                        0                         0   

   embarked_from_southampton  
0                          1  
1                          0  
2                          1  
3                          1  
4                          1

In [39]:
X_test = df.drop(['survived'], axis=1).values

In [40]:
X_test[:5]

array([[3, 22.0, 1, 0, 7.25, 1, False, 0, 0, 1],
       [1, 38.0, 1, 0, 71.2833, 0, False, 1, 0, 0],
       [3, 26.0, 0, 0, 7.925, 0, False, 0, 0, 1],
       [1, 35.0, 1, 0, 53.1, 0, False, 0, 0, 1],
       [3, 35.0, 0, 0, 8.05, 1, False, 0, 0, 1]], dtype=object)

### 3. Setup the model

In [26]:
# Set up the model
model = Sequential()
type(model)

keras.engine.sequential.Sequential

In [41]:
# Save the number of input columns: n_cols
n_cols = X_train.shape[1]
n_cols

10

In [42]:
# Add the first hidden layer and input layer
model.add(Dense(32,
                activation='relu',
                input_shape=(n_cols,)
               )
         )


Instructions for updating:
Colocations handled automatically by placer.


In [43]:
# Add the output layer
model.add(Dense(2,
                activation='softmax'
               )
         )

### 4. Compile the model

In [44]:
# Compile the model
model.compile(optimizer='sgd', 
              loss='categorical_crossentropy', 
              metrics=['accuracy'])

### 5. Fit the model

In [46]:
# Fit the model
model.fit(X_train, y_train,epochs=10)

Epoch 1/10
891/891 [==============================] - 0s 76us/step - loss: 1.6594 - acc: 0.6240
Epoch 2/10
891/891 [==============================] - 0s 72us/step - loss: 1.1064 - acc: 0.6296
Epoch 3/10
891/891 [==============================] - 0s 30us/step - loss: 0.6860 - acc: 0.6633
Epoch 4/10
891/891 [==============================] - 0s 40us/step - loss: 0.6538 - acc: 0.6723
Epoch 5/10
891/891 [==============================] - 0s 35us/step - loss: 0.5920 - acc: 0.6869
Epoch 6/10
891/891 [==============================] - 0s 40us/step - loss: 0.6248 - acc: 0.6902
Epoch 7/10
891/891 [==============================] - 0s 40us/step - loss: 0.6274 - acc: 0.6970
Epoch 8/10
891/891 [==============================] - 0s 40us/step - loss: 0.5901 - acc: 0.6914
Epoch 9/10
891/891 [==============================] - 0s 51us/step - loss: 0.6074 - acc: 0.6835
Epoch 10/10
891/891 [==============================] - 0s 31us/step - loss: 0.5787 - acc: 0.7015


### 6.3. Make Predictions on new data / test data

In [53]:
# Calculate predictions: predictions
y_pred = model.predict(X_test)